// <auto-generated />
using BizimBahceDatabaseWork.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BizimBahceDatabaseWork.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221023211000_Add")]
    partial class Add
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BizimBahceDatabaseWork.Models.Entities.OliveOil", b =>
                {
                    b.Property<int>("OliveOilsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OliveOilBenefitID")
                        .HasColumnType("int");

                    b.Property<int>("OliveOilPriceID")
                        .HasColumnType("int");

                    b.Property<int>("OliveOilPropertyID")
                        .HasColumnType("int");

                    b.Property<int>("OliveOilTypeID")
                        .HasColumnType("int");

                    b.HasKey("OliveOilsID");

                    b.ToTable("OliveOils");
                });
#pragma warning restore 612, 618
        }
    }
}
